Make TS compile first

diff --git a/executables/ts/run b/executables/ts/run
--- a/executables/ts/run
+++ b/executables/ts/run
@@ -15,6 +15,19 @@ DEST="$1" ; shift
 MEMLIMIT="$1" ; shift
 MAINSOURCE="${ENTRY_POINT:-$1}"
 
+DESTCLI="${DEST}.js"
+
+# JS compile:
+tsc --outFile ${DESTCLI} ${MAINSOURCE}
+EXITCODE=$?
+[ "$EXITCODE" -ne 0 ] && exit $EXITCODE
+
+# Check for output file:
+if [ ! -f "$DESTCLI" ]; then
+	echo "Error: JS compiled file '$DESTCLI' not found."
+	exit 1
+fi
+
 # Report the entry point, so it can be saved, e.g. for later replay:
 if [ -z "$ENTRY_POINT" ]; then
 	echo "Info: detected entry_point: $MAINCLASS"
@@ -34,7 +47,7 @@ fi
 # debugging.
 # export ONLINE_JUDGE=1 DOMJUDGE=1
 
-exec ts-node "$MAINSOURCE" "\$@"
+exec node "$DESTCLI" "\$@"
 EOF
 
 chmod a+x "$DEST"
